version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=paiwr
    container_name: db
    ports:
      - 5432:5432
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    environment:
      DB_CONN_STR: postgresql://root:secret@db:5432/paiwr?sslmode=disable
      PORT: 8080
      JWT_SECRET: secret
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./server/:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app
