name: Run tests

on:
  push:
    branches:
      - main
    paths:
      - server/**

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: server/go.mod
          cache: true
          cache-dependency-path: server/go.sum

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        working-directory: server
        run: golangci-lint run --verbose --out-format=github-actions

      - name: Build
        working-directory: server
        run: go build -v ./...

      - name: Test
        working-directory: server
        run: go test -v ./...
